name: Build APK Final 2026

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v4

      - name: Instalar Dependencias del Sistema
        run: |
          sudo apt update
          sudo apt install -y build-essential git python3-dev libncurses5-dev libffi-dev libssl-dev ccache cmake libtool pkg-config autoconf automake libltdl-dev
          pip3 install --user --upgrade Cython==0.29.33 buildozer virtualenv

      - name: Compilar APK
        run: |
          # 1. Aceptar licencias
          export APP_ANDROID_ACCEPT_SDK_LICENSE=True
          
          # 2. En lugar de 'clean', borramos solo la carpeta de la plataforma 
          # para forzar a python-for-android a reinstalarse correctamente
          rm -rf .buildozer/android/platform
          
          # 3. Ejecutar la compilación directamente
          # Usamos la ruta completa para asegurar que encuentre el ejecutable
          ~/.local/bin/buildozer android debug

      - name: Subir APK
        uses: actions/upload-artifact@v4
        with:
          name: CodeQuest-Debug
          path: bin/*.apk
